language: python

matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install pytest coveralls matplotlib flake8
  - python setup.py install

script:
  - pytest

  - flake8 --exit-zero trendvis

after_success:
  coveralls
